export const wholesome = 
[
    "You're that “Nothing” when people ask me what I'm thinking about.",
    "Our system of inside jokes is so advanced that only you and I get it. And I like that.",
    "Is that your picture next to “charming” in the dictionary?",
    "If cartoon bluebirds were real, a bunch of them would be sitting on your shoulders singing right now.",
    "Did you know that you're like sunshine on a rainy day?",
    "You're more fun than a ball pit filled with candy. (And seriously, what could be more fun than that?)",
    "That thing you don't like about yourself is what makes you so interesting.",
    "Everyday is just BLAH when I don't see you For reals!",
    "You're better than a triple-scoop ice cream cone. With sprinkles.",
    "Everyone gets knocked down sometimes, but you always get back up and keep going.",
    "Being around you is like being on a happy little vacation.",
    "You're a candle in the darkness.",
    "You're even better than a unicorn, because you're real.",
    "You are more fun than anyone or anything I know, including bubble wrap.",
    "You're my favorite daydream.",
    "When I walk into a room full of people, I always look for you first.",
    "I want you to know something, but I don't know how to tell it. So I'll let the first three words of this explain it.",
    "One day I caught myself smiling without no reason, then I realized I was thinking of you.",
    "You're a flamingo in a flock of pigeons.",
    "No matter how you feel, get up, dress up, show up, and never give up.",
    "Hey you. Stop being so cute.",
    "You're a natural at whatever you do!",
    "You're the sweetest—you don't have a mean bone in your body do you?",
    "You are more amazing than you realize.",
    "Not everyone can pull off that look, but you sure can!",
    "You're the most thoughtful person I've ever met",
    "Your heart is so big, I can hear it beating from a mile away.",
    "I wish I could put you in my pocket and take you everywhere I go.",
    "Please never stop being you!",
    "Your heart must be ten times the average size.",
    "You're such a ray of sunshine.",
    "Is there anything you can't do?",
    "Always remember that you're an amazing person.",
    "Wow! You look awesome today.",
    "Thank you for coming here. You make me feel less lonely.",
    "Always remember that someone in this world, is currently thinking about you.",
    "Damn! That dress looks amazing. I want your closet.",
    "Hey! I was just thinking about you. I hope you're doing well.",
    "Your smile makes my day!",
    "Please be happy, 'cause when you're happy, I'm happy.",
    "You're a 11 out of 10.",
    "Hey, has anyone told you that your hairstyle looks amazing today?"
]